#Shimeji-ee Configuration Options
#Thu Jun 05 03:35:59 MDT 2025
Filter=nearest
Opacity=1.0
MenuDPI=120
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger
AlwaysShowShimejiChooser=false
Environment=generic
Scaling=1.0
ActiveShimeji=Shimeji
AlwaysShowInformationScreen=false
