#Shimeji-ee Configuration Options
#Wed Apr 28 22:37:22 CDT 2021
MenuDPI=96
Language=en-GB
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger/\uBA54\uBAA8\uC7A5/Chrome/\uCE74\uCE74\uC624\uD1A1/CLIP STUDIO PAINT/Discord
Scaling=1
Breeding=false
ActiveShimeji=Shimeji
